---
- hosts: 10.7.1.5

  become: yes
  become_user: "{{ lookup('env','USER') }}"
  tasks:

  # Crear Volumen de Portainer
  # --
  #
  - name: Create new Volume
    community.docker.docker_volume:
      name: portainer-data

  # Desplegar Portainer
  # --
  #
  - name: Deploy Portainer
    community.docker.docker_container:
      name: portainer
      image: "docker.io/portainer/portainer-ce"
      ports:
        - "9000:9000"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer-data:/data
      restart_policy: always
